version: "3"
services:
  app:
    hostname: aarehack1
    container_name: aarehack1
    image: node:alpine
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    command: yarn build
    expose: [3000]